name: Generate debug keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: keytool
        run: |
          keytool -genkey -v \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36500 \
            -dname "CN=Android Debug,O=Android,C=US"
          ls -la debug.keystore
      - uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: debug.keystore
          if-no-files-found: error
